// <auto-generated />
namespace LL191567Taller1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Validaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "202309110335268_Validaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
